### PR TITLE
Next release 1.5.4

### PR DESCRIPTION
**Pull request by soncaokim**
Initially this PR is created to start a review process for the next release.
However, I just realised that the existence of the new tag (1.5.4) has triggered a build and release to PlayStore (cf https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/6512049004) - oops, this is not intentional.

### CODE REVIEW

**Review by AdrienPoupa — APPROVED** [review]

**Comment by AdrienPoupa** [comment]
Since the tag has the appropriate changes, all good! Looks like it got pushed to the Play Store successfully :)

**Comment by soncaokim** [comment]
We need to revise the prepare-new-release script, or the pipeline, to avoid
rushing a release like that.

**Comment by AdrienPoupa** [comment]
This is basically where Semantic Release could help imo https://github.com/semantic-release/semantic-release

There could be a manual action on each `master` pipeline that could trigger the prepare-new-release, the tag creation and other which would in turn trigger the Play Store build.

**Comment by soncaokim** [comment]
> looking at the `prepare-new-release` script, we could probably apply some small modifications to have it working

Please do!
Merging this for now - to avoid further confusion on the release

**Comment by soncaokim** [comment]
> This is basically where Semantic Release could help imo https://github.com/semantic-release/semantic-release

The first step to get there would be to have a kind of discipline in commit message, enforcing the sem-rel convention.
i.e. adding commit linter on the CI chain to blame the wrong message/bad author, or even reject the commit.

**Pull request merged**
