### PR TITLE
feat(translations): add missing Dutch strings

### PR DESCRIPTION
**Pull request by AnonymousWP**
First of all: thanks for this great project. Probably the best music player I used so far.

---
This adds a lot of missing Dutch translations.

To the developers: it's better to always update the strings for each localisation. This time I had to use a diff-checker to see which strings were new and then manually add them. I added the strings now, later I'll translate them to Dutch.

### CODE REVIEW

**Comment by soncaokim** [comment]
> To the developers: it's better to always update the strings for each localisation.

Hi, I'm refraining from doing this since this would basically mean I'd update the strings with automatic translation that I dont understand nor verify.

Thanks for the PR, please let me know when this is ready to merge.

**Comment by AnonymousWP** [comment]
> > To the developers: it's better to always update the strings for each localisation.
> 
> Hi, I'm refraining from doing this since this would basically mean I'd update the strings with automatic translation that I dont understand nor verify.

I think you misunderstood what I said, or maybe I didn't explain it correctly. Basically, and that's what usually happens with a lot of other apps is the following:

1. Developer adds new features
2. New features come with new (English by default) strings
3. Developer adds those new strings (in English, so not translated yet) to all other localisation files `nl/strings.xml`

In this case, number 3 has not been performed, which means I had to check which strings were new by using an online difference checker.

Does this make more sense? I'm not asking you to translate stuff by yourself, but to at least show the English (untranslated) strings in every `strings.xml`, so that people like me know what's left to be translated.

**Comment by soncaokim** [comment]
Understood. There should be tool that eases the work for both of us - I'll try to have a look when time allows.

**Comment by AnonymousWP** [comment]
> Understood. There should be tool that eases the work for both of us - I'll try to have a look when time allows.

A colleague of mine said this should be possible with either regex or a utility within your IDE. Perhaps Android Studio can do it? See https://developer.android.com/studio/write/translations-editor#addlanguage.

**Comment by AnonymousWP** [comment]
But what I'm sure about is that this is very confusing: how will I know whether I'm going to be translating all strings or there are still some missing ones? The amount of lines don't even correspond:

image

**Comment by soncaokim** [comment]
> Understood. There should be tool that eases the work for both of us - I'll try to have a look when time allows.

In Android Studio there is a "Translation Editor" that is quite helpful. It highlights what needs to be translated per language

image

**Comment by soncaokim** [comment]
It this ready to merge?

**Comment by AnonymousWP** [comment]
> > Understood. There should be tool that eases the work for both of us - I'll try to have a look when time allows.
> 
> In Android Studio there is a "Translation Editor" that is quite helpful. It highlights what needs to be translated per language
> 
> image

Yeah, so this should help you in the future to synchronise all translations so that new strings are introduced in all localisation files?

> It this ready to merge?

Yep, which is why I marked it as ready for review. 😉

**Comment by soncaokim** [comment]
> Yeah, so this should help you in the future to synchronise all translations so that new strings are introduced in all localisation files?

No, replicating the same untranslated string on N languages is not the way to me.

When time allows, I'll investigate on integrating online tools that provides the same feature as the Studio's Translation editor. The idea is to lower the barrier for translation contributors, not everyone is fluent or equipped with diff, github and Android Studio.

Pretty sure that such thing exists :-)

--

Thanks for this PR. Merging this.

**Review by soncaokim — APPROVED** [review]

**Comment by soncaokim** [comment]
Arf, the build failed (see hereunder). Is it possible to review this and reopen the PR please?
For now I'm reverting the merge.

Thanks

image

**Pull request merged**
