### PR TITLE
Fix snackbar unreadable text

### PR DESCRIPTION
**Pull request by soncaokim**
On light theme, the snackbar text was black on dark grey.

### CODE REVIEW

**Comment by Octoton** [comment]
Seems like in dark mode the snackbar is reverse, why not having a white snackbar with dark text in light mode and a dark on white in dark mode ?
Screenshot_20230228-211923
Screenshot_20230228-212105
Screenshot_20230228-212147

**Comment by soncaokim** [comment]
@Octoton Are we good to go or the (default) inverse snackbar is a blocker for you?

**Comment by Octoton** [comment]
> @Octoton Are we good to go or the (default) inverse snackbar is a blocker for you?

Inverse snackbar is not a problem as google choice are just strange, however in dark theme the color background is a blocker for me as it should follow google color
For example youtube:
Screenshot_20230305-213050~2

And for this it seems like the icon need to have a color variant for dark mode

**Comment by soncaokim** [comment]
In dark mode, you'd expect to have white background instead of a greyish white, correct?

**Comment by Octoton** [comment]
> In dark mode, you'd expect to have white background instead of a greyish white, correct?

Yes

**Comment by soncaokim** [comment]
> > In dark mode, you'd expect to have white background instead of a greyish white, correct?
> 
> Yes

If you have any idea on how this can be achieved, please tell me.
I'm not familiar with this theming stuff.

**Comment by Octoton** [comment]
Did some test and we can do:

**Comment by Octoton** [comment]
Did some test and we could do:

>     <style name="snackbar_style_dark" parent="@style/Widget.MaterialComponents.Snackbar">
>         <item name="backgroundTint">@color/ate_primary_text_dark</item>
>         <item name="android:textColor">@color/md_black_1000</item>
>         <item name="animationMode">slide</item>
>     </style>m
> 
>     <style name="snackbar_style_light" parent="@style/Widget.MaterialComponents.Snackbar">
>         <item name="backgroundTint">@color/ate_primary_text_light</item>
>         <item name="android:textColor">@color/md_white_1000</item>
>         <item name="animationMode">slide</item>
>     </style>

The problem with this is that when removing a item from queue the cancel button is not visible in dark mode (what I don't understand is why the cancel button in dark mode is white instead of like in light mode: the color of the album art - something todo with `snackbar.setActionTextColor(getBackgroundColor(activity));` in PlayingQueueAdapter.java)

Moreover, when reloading the library the music icon will become not visible as it is white (didn't check where in the implem this is set to manage this case)

**Comment by soncaokim** [comment]
@Octoton , I think the last 3 commits deal with the remark you shared.

> what I don't understand is why the cancel button in dark mode is white instead of like in light mode: the color of the album art

This is an existing issue (see https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/701) and is probably linked to an condition here
https://github.com/VinylMusicPlayer/VinylMusicPlayer/blob/d7743f5b00c73bafacdf0c03128a583e92913960/app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java#L463

**Review by Octoton — APPROVED** [review]

**Pull request merged**
