### PR TITLE
Preps for 1.5.0

### PR DESCRIPTION
**Pull request by soncaokim**

### CODE REVIEW

**Comment by Octoton** [comment]
Why not condensed some information, like:

> Queue change confirmation by @soncaokim and @Octoton in  https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/658, https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/679

Same could be done for markdown visualisation/licenses rework

**Comment by Octoton** [comment]
Other than that, thanks for all the work you have done to unable this update

**Comment by Octoton** [comment]
A little question that is indirectly related to this:
Is it normal than on F-droid the app page as no icon nor header or screenshot  to present the app ?

**Comment by soncaokim** [comment]
> Why not condensed some information, like:
> 
> > Queue change confirmation by @soncaokim and @Octoton in  #658, #679
> 
> Same could be done for markdown visualisation/licenses rework

Because I'm lazy and this relnotes is collected by a bot (cf the config file I've set in .github/release.yml).
I've removed some PR that I consider minor.

**Comment by soncaokim** [comment]
> A little question that is indirectly related to this: Is it normal than on F-droid the app page as no icon nor header or screenshot to present the app ?

Dont know. May be @AdrienPoupa ?

**Comment by soncaokim** [comment]
@AdrienPoupa Can you please have a look on this PR?

**Comment by AdrienPoupa** [comment]
> > A little question that is indirectly related to this: Is it normal than on F-droid the app page as no icon nor header or screenshot to present the app ?
> 
> Dont know. May be @AdrienPoupa ?

No it is not, but I guess it has something to do with changing the repo URL. Something must have broke in their script, since we have not changed anything on our side.

**Review by AdrienPoupa — APPROVED** [review]

**Pull request merged**
