### PR TITLE
Pref export/import

### PR DESCRIPTION
**Pull request by soncaokim**

### CODE REVIEW

**Comment by soncaokim** [comment]
Hi @TheFireCircle 

Related to a previous comment https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/946#discussion_r1536659313

>> After importing another color the app looks like this in my case:
>
>Your screenshot looks correct (the top and bottom UI shares the same color as the "Settings" title bar). IIRC mine was not on the same color. If I can reproduce this I'll let you know.

I've reproduced the issue with the latest merge, in the screenshot here under:
- The top bar is not the same color as the title bar.
- The primary/accent colors are not correctly shown. Here I've customized it, but the Setting screen shows the defaut (factory) values
Screenshot_20240514-222711

**Comment by TheFireCircle** [comment]
> Hi @TheFireCircle
> 
> Related to a previous comment [#946 (comment)](https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/946#discussion_r1536659313)
> 
> > > After importing another color the app looks like this in my case:
> > 
> > 
> > Your screenshot looks correct (the top and bottom UI shares the same color as the "Settings" title bar). IIRC mine was not on the same color. If I can reproduce this I'll let you know.
> 
> I've reproduced the issue with the latest merge, in the screenshot here under:
> 
>     * The top bar is not the same color as the title bar.
> 
>     * The primary/accent colors are not correctly shown. Here I've customized it, but the Setting screen shows the defaut (factory) values
> 
> 
> 

Hi, thanks for reproducing this issue.
What where the steps you've done to produce this behavior and which API level does your OS use?

**Comment by soncaokim** [comment]
Hmm, by trying to reproduce it on emulator, I can't do it consistently. 

The screenshots were taken on real devices, running either Android 14/Google skin or Android 13/Lineage skin.

**Comment by TheFireCircle** [comment]
> Hmm, by trying to reproduce it on emulator, I can't do it consistently.
> 
> The screenshots were taken on real devices, running either Android 14/Google skin or Android 13/Lineage skin.

Hi, I've tried to reproduce it on emulator but it I could not reproduce it.
What do you think, how we should continue with this PR?

**Comment by soncaokim** [comment]
Hi,

Let me have a look again in the next few days.
If not reproducible, then we merge.

S.

**Pull request merged**
