### PR TITLE
allow genre splitting based on typical split characters

### PR DESCRIPTION
**Pull request by gaycodegal**
re: #773 

edit 2:

I have verified this change is compliant with all existing genre uses in the app, and should not cause issues.

edit:
from linux if you want to set multiple genres for a song you can do

```bash
eyeD3 YOUR_SONG --genre="Alternative;Indie"
```

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
Thanks for your contribution! Looks good to me, @soncaokim any thoughts?

**Comment by soncaokim** [comment]
Hi,

This looks ok to me. Let me play with it for few days and will get back to you.

Happy 2024

**Review by soncaokim — APPROVED** [review]
lgtm

**Comment by soncaokim** [comment]
I have one additional request for this feature:

Can you please modify the tag editor screens (per song and per album) so that one can visually modify the genres, in the same model as the artists, ie multi-line text field, one line per genre. The field name/hint should be changed as well to indicate this.

Thanks

**Comment by gaycodegal** [comment]
Yeah sure can do

**Pull request merged**
