### PR TITLE
Refactor Licenses dialog

### PR DESCRIPTION
**Pull request by soncaokim**
This fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/677

### CODE REVIEW

**Comment by soncaokim** [comment]
> For the first 2 errors, creating reports/licenses/ folder by hand resolved the issue but it should be done by the script when needed.
> For the third error I had to remove the LICENSES.md, I thinks the script should do it on is own

Thanks for double checking this, I just realised that the part of the script handling copied source code didnt work.
These errors are fixed in the last commit.

> Lastly, I am curious, how did you configured gradlew on your bash terminal for it to not trow out this error

I dont have such error, nor needed to explicitly specify the java home in .properties

**Review by Octoton — APPROVED** [review]
Work like a charm

**Comment by soncaokim** [comment]
@AdrienPoupa Are we good to merge this in?

**Review by AdrienPoupa — APPROVED** [review]

**Comment by AdrienPoupa** [comment]
Sure, go ahead! Thanks

**Pull request merged**
