### PR TITLE
Add settings to opt-in for crash report

### PR DESCRIPTION
**Pull request by soncaokim**
Add a new setting to control the crash report collection (by default is disabled).

(There is a pending extensive refactoring of this oops-handler, aim to be less instrusive - will push in another PR).

### CODE REVIEW

**Comment by soncaokim** [comment]
> @soncaokim Wasn't this supposed to be opt-in? I went to check to enable it in case it could help solving #542 (which is still ongoing), but found out it was checked.

My mistake, fixed in #868 (you can still disable it manually)

> Also, is the report shown to the user and editable before it's sent (which is always nice to see what exactly is sent, and where, regarding user privacy).

The app wont submit anything. The current workflow is that you open the Github issue report page, paste in the collected crash report (or not), edit/amend/add or remove relevant info. Then submit it.

**Comment by soncaokim** [comment]
Nothing prevents you to ignore the "submit" button, and capture the crash report in clipboard, paste it to Google Keep/to a sync'ed memo/or email it to yourself. I wont push it any further, that's beyond this simple **offline** music player  :-)

The diff you asked - tell me if this answers your question: In the case where an overlooked problem arise (an exception), we try to manage it and downgrade the experience accordingly - music continues, but without the failed feature (tags, lyrics, cover, sound effect, etc). If the crash collection is enabled, then the technical error is captured and can be shared to better handle it if possible.

Some time there are exceptions that are not managed -> the app stops. No music.

**Comment by soncaokim** [comment]
> So, if I sum up correctly, an uncaught exception should trigger the crash reporter, whether it crashes the application or not, but a caught one should do nothing? Are the caught exception also printed in logs?

Let's say there are three levels:
- An uncaught exception stops the apps and leave it to the system (Android OS). The OS shows "app crashed" dialog, you may have the crash logged in adb. It may try to restart the app.
- We try to catch exception at the "root" level of the app. There is no way to manage the error/downgrade the experience here. The system is not aware, only the app is - and it proposes a crash reporting dialog. No log in adb.
- A caught and managed exception, linked to a feature/function inside the app: App continues, with downgraded experience. The system is not aware, only the app is - No log in adb, crash reporter is proposed if you enabled the in-app crash collection.

**Comment by soncaokim** [comment]
> Then I'm still seeing exceptions in logs not crashing the application

Dont hesitate to iterate on this. It's possible that I've missed cases. Thanks!

**Review by GregKruz — CHANGES_REQUESTED** [review]
Hack

**Pull request merged**
