### PR TITLE
upstream-contrib: Queue change confirmation

### PR DESCRIPTION
**Pull request by soncaokim**
Prevent accidental play when browsing library/folder/playlists. 
Instead of implicit "Play the item now with all others listed, and discard what ever ongoing", a somewhat polite dialog lets the user to chose among different options.

- [x] Save the last chosen choice to pref, and reuse that next time.
- [x] Todo tags (strings, etc)

### CODE REVIEW

**Review by AdrienPoupa — APPROVED** [review]

**Comment by soncaokim** [comment]
> when you click in the middle of a list the popup is saying that x number of item will be added, with x being the total number of item in this list and not the number that are after where we are clicking (the song we clicked on should be included) 

This should be the case already. I'll check

> This should be sweet to have an option to disable this pop-up if people want (by default the popup should be seen)

This is the original behaviour, and I think it is too easy to loose the playing queue with that.

**Comment by soncaokim** [comment]
Thanks for the comment. I'd stick with this "always safe" proposition for now, if there are complaints we can revisit this.

The changes for the song count comes with the PR https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/670

**Comment by not-my-profile** [comment]
Just some user feedback: I find the new dialog to be very annoying. When I click on a song I want it to play instantly. I don't want to click twice every time.

**Comment by sectopodwreck** [comment]
Sorry man, but this feature has been more like a inconvenience, especially when album hopping. Since the app doen't clear the queue after my previous session, it will always pop up.

Adding extra button presses for a common function starts to become tedious real quick. 

If you can please set this as an option in the settings, that would be great.

**Comment by brunetton** [comment]
> 

Exactly; this is super strange to see "you're going to add x tracks in playing queue" when adding only one file. I double checked to be sure I didn't clicked on a folder, but no.

**Pull request merged**
