### PR TITLE
Fix multi genres

### PR DESCRIPTION
**Pull request by soncaokim**
Add missing implementation to support multi-genre (loading and saving)

### CODE REVIEW

**Comment by soncaokim** [comment]
@gaycodegal There is actually more to do with mutli-genres support - I overlooked this part as well.

This PR provides necessary missing bits for that. Otherwise genres filled with '\n' (from the tag editor screens) wont be interpreted correctly.

**Comment by gaycodegal** [comment]
@soncaokim oh thanks for the catch. I hadnt checked unicode normalization, or perhaps it was that i didnt check full app boot cycle. One question though, is Song.toString used anywhere important? it looks like something that could be vulnerable to injection attacks if its used in anything important, such as being interpreted as code. we might wish to escape our values for all fields to prevent malicious uses if this is indeed used anywhere as code / with a database

**Comment by gaycodegal** [comment]
like for example, users can store newlines in any field regardless of if we personally want them to or not. If genres broke it, conceivably other fields may as well; we just dont test for that

**Comment by gaycodegal** [comment]
and also what about single quote injections - does unicode normalization safeguard against that or not

**Comment by soncaokim** [comment]
Hi, as of now, the app does nothing special to prevent SQL injection, beside some common practice such as replacement parameter or query (cf https://developer.android.com/privacy-and-security/risks/sql-injection)

**Comment by gaycodegal** [comment]
@soncaokim ah ok so that is SQL then. I'll fix it when I have time

**Review by GregKruz — APPROVED** [review]

**Pull request merged**
