### PR TITLE
theme experiments

### PR DESCRIPTION
**Pull request by soncaokim**
Feature proposal:
- [x] use album colors (ie. a la Playing screen) to override theme primary and accent colors. The app color will change according to the playing song (except album and artist page, where it follows the album/artist cover art colors).
- [x] richer/colorful miniplayer
- [x] use theme accent color to highlight destructive menu item

Devel/Testing check list:
- [x] miniplayer text color is not the same (and not as good) as viewpager one
- [x] status bar background on main activity is a bit darker comparing to album/artist detail activities
- [x] miniplayer playing song name is not in bold when changing song/changing activity
- [x] library screen: Make the view pager indicator (now in accent color) thicker and more visible
- [x] the primary color used for menu text/shuffle item is not chosen with consideration of dark/light theme (ie background)
- [x] folder view: the breadcrumbs color is not the same as toolbar
- [x] bug https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/691
- [ ] bug https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/692
- [x] If the primary color is a vibrant red or blue, the auto-generated accent color is the same as primary one
- [ ] screen flickers on song change, especially when resuming after multiple songs are played. Intermediate colors are applied -> should go/blend directly to the last color.
- [ ] playlist detail screen: doesnt switch colour on song change
- [ ] toast/snackbar color inconsistencies (white text on light theme/black text on dark background) 
- [ ] refactoring and todo

### CODE REVIEW

**Comment by soncaokim** [comment]
@AdrienPoupa @Octoton I'd like to introduce this new feature to the app: the app color scheme follows the playing song's cover art color. In another words, this extends the "Now playing" screen coloring to the whole app.

There are still rough edges and todo/refactoring, but the concept is working.

Is this something that you'd accept to merge into the app?

**Comment by Octoton** [comment]
I like the idea, however I think this need to be a setting option so people can opt out and keep there specific primary/secondary.

After trying it a little, some remark:
 - when randomly listening to song, the color change flash the screen a lot. If we want to do this, there need to be a smooth transition between color
 - there need to be a fail safe for text so there are always visible (on dark or light background)
 
 example of illegible text:
Screenshot_20230211-155226~2
Screenshot_20230211-155218~2
Screenshot_20230211-155640~2
Screenshot_20230211-155636~2

**Comment by soncaokim** [comment]
Thanks for trying. Yes there are rough edges, I just want to have a feedback on the concept before moving on.

**Comment by NoahJelen** [comment]
Mind if I tinker with this? I know how to code in Java and I have a [desktop music player](https://gitlab.com/aercloud-systems/music-lounge) with the ability to be dynamically themed according to the color palette of the current song art.

**Comment by soncaokim** [comment]
> Mind if I tinker with this? I know how to code in Java and I have a [desktop music player](https://gitlab.com/aercloud-systems/music-lounge) with the ability to be dynamically themed according to the color palette of the current song art.

Hey, this is open source, feel free to clone and experiement with it,
You can submit the change to this branch, I will review.

**Pull request closed without merging**
